name: Release Webshop

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0, v1.1

jobs:
  build-linux:
    name: Build and Release for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build Linux binary using Makefile
        run: make

      - name: Rename Linux binary for release
        run: mv build/webshop build/webshop-linux

      - name: Create GitHub Release (if needed)
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Upload Linux binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/webshop-linux
          token: ${{ secrets.PERSONAL_TOKEN }}

  build-windows:
    name: Build and Release for Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build Windows binary using Makefile
        run: make windows

      - name: Upload Windows binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/webshop.exe
          token: ${{ secrets.PERSONAL_TOKEN }}
